version: 2

updates:
  - package-ecosystem: "npm"
    ignore:
      # Playwright has to be updated in the workflows at the same time,
      # so dependabot can't update it automatically.
      - dependency-name: "playwright"
    directories:
      - "/"
      - "/demo"
      - "/packages/grad-vue"
      - "/packages/grad-vue-rte"
    schedule:
      interval: "weekly"
    groups:
      monorepo-dependencies:
        group-by: dependency-name