name: Dependabot Tests

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.62.1-noble@sha256:dcc5531e97840b9b5e794f2814476b21571c5124a3fca2267d73041f56e7580e # ratchet:mcr.microsoft.com/playwright:v1.62.1-noble
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Web Components Test
        run: npm run test:wc
